# Generated by Django 4.2 on 2023-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Iris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sepal_length", models.FloatField()),
                ("sepal_width", models.FloatField()),
                ("petal_length", models.FloatField()),
                ("petal_width", models.FloatField()),
                ("predicted_class", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
